import {
  AlertTriangle,
  Bell,
  Bookmark,
  Box,
  Bug,
  Check,
  Cloud,
  CloudDownload,
  CloudUpload,
  Code,
  Cog,
  Container,
  Copy,
  Cpu,
  Database,
  Download,
  Eye,
  ExternalLink,
  File,
  FileCode,
  FileText,
  Files,
  Flame,
  FlaskConical,
  Folder,
  FolderOpen,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Globe,
  Hammer,
  HardDrive,
  Heart,
  Info,
  Key,
  Layers,
  Link,
  List,
  Lock,
  Package,
  Play,
  Plus,
  Rocket,
  RotateCcw,
  Save,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  Tag,
  Terminal,
  TestTube,
  Trash2,
  Unlock,
  Upload,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Icon slugs available to toolbar buttons. Ported from Arkadia's
 * `src/icons.ts`. A persisted `icon` string that isn't in this map (e.g. from
 * an older or forked build) resolves to `null` via {@link getToolbarIcon}
 * instead of crashing the render.
 */
export const TOOLBAR_ICONS: Record<string, LucideIcon> = {
  play: Play,
  square: Square,
  "rotate-ccw": RotateCcw,
  rocket: Rocket,
  zap: Zap,
  sparkles: Sparkles,
  flame: Flame,
  hammer: Hammer,
  wrench: Wrench,
  cog: Cog,
  settings: Settings,
  "sliders-horizontal": SlidersHorizontal,
  bug: Bug,
  "flask-conical": FlaskConical,
  "test-tube": TestTube,
  terminal: Terminal,
  code: Code,
  "file-code": FileCode,
  "git-branch": GitBranch,
  "git-commit": GitCommit,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  box: Box,
  package: Package,
  database: Database,
  server: Server,
  container: Container,
  globe: Globe,
  "external-link": ExternalLink,
  link: Link,
  "share-2": Share2,
  folder: Folder,
  "folder-open": FolderOpen,
  file: File,
  "file-text": FileText,
  files: Files,
  check: Check,
  x: X,
  "alert-triangle": AlertTriangle,
  info: Info,
  plus: Plus,
  copy: Copy,
  "trash-2": Trash2,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  shield: Shield,
  cloud: Cloud,
  "cloud-upload": CloudUpload,
  "cloud-download": CloudDownload,
  cpu: Cpu,
  "hard-drive": HardDrive,
  eye: Eye,
  search: Search,
  save: Save,
  download: Download,
  upload: Upload,
  layers: Layers,
  list: List,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  tag: Tag,
  bell: Bell,
};

export const TOOLBAR_ICON_NAMES = Object.keys(TOOLBAR_ICONS);

export function getToolbarIcon(name: string | undefined): LucideIcon | null {
  if (!name) return null;
  return TOOLBAR_ICONS[name] ?? null;
}
